title: Ali Arastehfard
description: Personal site for applied cryptography research and updates.
url: "https://aliarastehfard.github.io"
baseurl: ""
social_image: "/assets/images/tennisfan.JPG"

markdown: kramdown
permalink: /blog/:title/

collections:
  posts:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      published: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

exclude:
  - push.sh
